name: Test

on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/pnpm-lock.yaml') }}
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pnpm install && pnpm exec playwright install
    - name: Run tests
      run: pnpm run test
